echo "### 1. Branding / Display Name"
echo "- android/app/src/main/res/values/strings.xml"
echo "- ios/App/App/Info.plist"
echo "- capacitor.config.ts"
echo "- app.json"
echo "- e2e/auth-bidding.spec.ts"
echo "- .github/workflows/deploy.yml"
echo "- HTML files (page2.html, page3.html, etc.)"
echo ""
echo "### 2. Domain / URL / CORS (redirect configuration)"
echo "- src/socket.ts"
echo "- src/server.ts"
echo "- mobile-app/App.js"
echo ""
echo "### 3. Test Data / Seed Data (Emails)"
echo "- seed_admin.ts, seed_admin.cjs, seed_all_roles.ts"
echo "- fix_admin_password.ts, fix_login_hint.cjs"
echo "- patch_admin_auth*.cjs"
echo "- test*.cjs, test-admin-login-fetch.js"
echo ""
echo "### 4. Technical Identifiers (Package / Bundle Identifiers)"
echo "- android/app/src/main/res/values/strings.xml (package_name, custom_url_scheme)"
echo "- android/app/src/main/java/com/transportconnect/app/MainActivity.java"
echo "- android/app/build.gradle"
echo "- ios/App/App.xcodeproj/project.pbxproj"
echo "- capacitor.config.ts (appId)"
echo "- app.json (package)"
