import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Button } from './ui/Button';
import { MapPin, Navigation, Camera, ShieldCheck, MessageCircle, Wallet, CheckCircle2, UploadCloud, Truck, ShieldAlert, Clock, CheckSquare, XCircle } from 'lucide-react';
import api from '../api/client';

type Tab = 'jobs' | 'active-trip' | 'earnings' | 'documents';

export default function DriverDashboard() {
  const [activeTab, setActiveTab] = useState<Tab>('jobs');
  const [sosActive, setSosActive] = useState(false);
  const [availableJobs, setAvailableJobs] = useState<any[]>([]);

  useEffect(() => {
    if (activeTab === 'jobs') {
      api.get('/loads').then(res => Array.isArray(res.data) && setAvailableJobs(res.data)).catch(err => console.error(err));
    }
  }, [activeTab]);

  const tabs = [
    { id: 'jobs', label: 'Job Offers', icon: Truck },
    { id: 'active-trip', label: 'Active Trip', icon: Navigation },
    { id: 'earnings', label: 'Wallet', icon: Wallet },
    { id: 'documents', label: 'Documents', icon: ShieldCheck },
  ] as const;

  return (
    <div className="flex h-full min-h-0 w-full flex-col overflow-hidden bg-[#f7f8fa] text-slate-900 dark:bg-slate-950 dark:text-slate-100">
      <header className="shrink-0 border-b border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
        <div className="mx-auto w-full max-w-5xl px-4 pb-3 pt-4 sm:px-6">
          <div className="flex items-start justify-between gap-3">
            <div>
              <div className="mb-2 flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-white"><Truck size={16}/></span><span className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Driver workspace</span></div>
              <h1 className="text-[25px] font-black tracking-[-0.03em] sm:text-3xl">Driver Hub</h1>
              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Trips, earnings and compliance in one place.</p>
            </div>
            <Button type="button" aria-label="Emergency SOS" onClick={() => setSosActive(!sosActive)} className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl p-0 ${sosActive ? 'bg-red-600 text-white animate-pulse' : 'border border-red-200 bg-red-50 text-red-600 hover:bg-red-100'}`}><ShieldAlert size={20}/></Button>
          </div>
          <nav aria-label="Driver navigation" className="mt-4 -mx-1 overflow-x-auto hide-scrollbar">
            <div className="flex min-w-max gap-1 px-1">
              {tabs.map(tab => { const Icon = tab.icon; const active = activeTab === tab.id; return <Button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`flex h-10 items-center gap-2 rounded-lg border px-3.5 text-xs font-bold whitespace-nowrap transition ${active ? 'border-slate-900 bg-slate-900 text-white dark:border-white dark:bg-white dark:text-slate-900' : 'border-transparent bg-transparent text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'}`}><Icon size={15}/>{tab.label}</Button>; })}
            </div>
          </nav>
        </div>
      </header>

      <main className="min-h-0 flex-1 overflow-y-auto overscroll-contain">
        <div className="mx-auto w-full max-w-5xl space-y-4 px-4 py-4 pb-28 sm:px-6 sm:py-6">
          {activeTab === 'jobs' && <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="space-y-4">
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Available jobs</p><p className="mt-2 text-2xl font-black">{availableJobs.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Driver status</p><p className="mt-2 text-sm font-black text-emerald-600">Available</p></div><div className="col-span-2 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 sm:col-span-1"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Today's focus</p><p className="mt-2 text-sm font-black">Find your next load</p></div></div>
            {availableJobs.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center dark:border-slate-700 dark:bg-slate-900"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-800"><Truck size={20}/></div><h2 className="mt-4 font-black">No jobs available right now</h2><p className="mt-1 text-xs text-slate-500">New matching loads will appear here.</p></div> : availableJobs.map(job => <article key={job.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-5"><div className="flex items-start justify-between gap-3"><div><span className="inline-flex items-center gap-1.5 rounded-full border border-brand-100 bg-brand-50 px-2.5 py-1 text-[10px] font-bold text-brand-700"><Clock size={12}/>{job.cargoType || 'Cargo'}</span><p className="mt-3 text-[10px] font-bold uppercase tracking-wider text-slate-400">Route</p></div><p className="text-lg font-black">₦{(job.suggestedBudget || 0).toLocaleString()}</p></div><div className="relative my-5 space-y-4"><div className="absolute bottom-4 left-[9px] top-4 w-px bg-slate-200 dark:bg-slate-700"/><div className="relative flex gap-3"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border-2 border-white bg-brand-100 dark:border-slate-900"><span className="h-2 w-2 rounded-full bg-brand-600"/></span><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Pickup</p><p className="text-sm font-bold">{job.origin}</p></div></div><div className="relative flex gap-3"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border-2 border-white bg-emerald-100 dark:border-slate-900"><MapPin size={10} className="text-emerald-600"/></span><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Dropoff</p><p className="text-sm font-bold">{job.destination}</p></div></div></div><div className="flex gap-2"><Button type="button" onClick={() => api.post('/bids/submit', { loadId: job.id, amount: job.suggestedBudget || 0, notes: 'Available immediately' }).then(() => alert('Bid submitted successfully!')).catch(e => alert('Failed to submit bid: ' + ((typeof e.response?.data?.error === 'object' ? JSON.stringify(e.response?.data?.error) : e.response?.data?.error) || e.message)))} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-brand-600 py-3 font-bold text-white"><CheckSquare size={17}/>Accept</Button><Button type="button" className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-red-200 bg-red-50 py-3 font-bold text-red-600"><XCircle size={17}/>Decline</Button></div></article>)}
          </motion.div>}

          {activeTab === 'active-trip' && <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="space-y-4"><section className="rounded-2xl bg-slate-950 p-5 text-white shadow-sm dark:bg-white dark:text-slate-950 sm:p-6"><div className="flex items-start justify-between gap-3"><div><span className="inline-flex rounded-full bg-emerald-400/15 px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-emerald-300">Live trip</span><h2 className="mt-3 text-2xl font-black">Apapa Port Delivery</h2><p className="mt-2 flex items-center gap-2 text-xs text-slate-300 dark:text-slate-600"><Navigation size={14}/>14 mins away · 5.2 km</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10 dark:bg-slate-100"><Navigation size={18}/></span></div><div className="mt-6 flex gap-2"><Button type="button" className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-white py-3 font-bold text-slate-950 dark:bg-slate-950 dark:text-white"><Navigation size={16}/>Navigate</Button><Button type="button" className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-white/15 bg-white/10 py-3 font-bold text-white dark:border-slate-200 dark:bg-slate-100 dark:text-slate-900"><MessageCircle size={16}/>Chat</Button></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-50 text-emerald-600"><CheckCircle2 size={17}/></span><div><h3 className="font-black">Delivery update</h3><p className="text-xs text-slate-500">Add proof before completing the trip.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3"><Button type="button" className="flex flex-col gap-2 rounded-xl border border-slate-200 bg-slate-50 p-4 text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><Camera size={22}/><span className="text-center text-[10px] font-bold">Cargo photos</span></Button><Button type="button" className="flex flex-col gap-2 rounded-xl border border-slate-200 bg-slate-50 p-4 text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><CheckSquare size={22}/><span className="text-center text-[10px] font-bold">Signature</span></Button></div><Button type="button" className="mt-3 w-full rounded-xl bg-emerald-600 py-3.5 font-black text-white">Complete Delivery <CheckCircle2 size={17}/></Button></section></motion.div>}

          {activeTab === 'earnings' && <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="space-y-4"><section className="rounded-2xl border border-slate-800 bg-slate-950 p-5 text-white shadow-sm dark:border-slate-700 dark:bg-slate-900 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Available balance</p><h2 className="mt-2 text-4xl font-black tracking-tight">₦124,500<span className="text-xl text-slate-400">.00</span></h2><div className="mt-6 flex items-end justify-between gap-3 border-t border-white/10 pt-5"><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">This week</p><p className="mt-1 font-bold text-emerald-400">+ ₦45,000</p></div><Button type="button" className="rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-slate-950">Withdraw</Button></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Activity</p><h3 className="mt-1 font-black">Recent transactions</h3></div><Wallet size={18} className="text-slate-400"/></div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-xs text-slate-500 dark:bg-slate-800">Transaction history will appear here.</div></section></motion.div>}

          {activeTab === 'documents' && <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Compliance</p><h2 className="mt-1 text-lg font-black">Your documents</h2></div><span className="rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-[9px] font-bold uppercase text-emerald-700">Verified</span></div><div className="mt-5 space-y-2">{[{title:"Driver's License",status:'Valid - Expires 2027'},{title:'Vehicle Inspection Report',status:'Valid - Expires Dec 2026'},{title:'Insurance Certificate',status:'Pending Review'}].map((doc,i)=><div key={i} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-800"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-white text-slate-500 dark:bg-slate-900"><ShieldCheck size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{doc.title}</p><p className={`mt-0.5 text-[9px] font-bold uppercase tracking-wider ${doc.status.includes('Pending') ? 'text-amber-600' : 'text-emerald-600'}`}>{doc.status}</p></div><Button type="button" aria-label="Upload document" className="rounded-lg bg-brand-50 p-2 text-brand-600"><UploadCloud size={16}/></Button></div>)}</div></section></motion.div>}
        </div>
      </main>
    </div>
  );
}
