import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Button } from './ui/Button';
import { MapPin, Navigation, Camera, ShieldCheck, MessageCircle, Wallet, CheckCircle2, UploadCloud, Truck, ShieldAlert, Clock, CheckSquare, XCircle } from 'lucide-react';
import api from '../api/client';

export default function DriverDashboard() {
  const [activeTab, setActiveTab] = useState<'jobs' | 'active-trip' | 'earnings' | 'documents'>('jobs');
  const [sosActive, setSosActive] = useState(false);
  const [availableJobs, setAvailableJobs] = useState<any[]>([]);
  useEffect(() => { if (activeTab === 'jobs') api.get('/loads').then(res => Array.isArray(res.data) && setAvailableJobs(res.data)).catch(err => console.error(err)); }, [activeTab]);
  const tabs = [
    { id: 'jobs', label: 'Job Offers', icon: Truck },
    { id: 'active-trip', label: 'Active Trip', icon: Navigation },
    { id: 'earnings', label: 'Wallet', icon: Wallet },
    { id: 'documents', label: 'Documents', icon: ShieldCheck },
  ] as const;
  return (
    <div className="relative z-0 flex h-full w-full flex-col bg-slate-50">
      <div className="relative z-20 mx-auto w-full max-w-lg space-y-4 p-4 pb-32 md:p-6 md:pb-32">
        <div className="flex items-center justify-between">
          <div><h1 className="text-3xl font-black tracking-tight text-slate-800 dark:text-slate-100">Driver Hub</h1><p className="text-sm font-medium text-slate-500 dark:text-slate-400">Ready for your next trip.</p></div>
          <Button type="button" aria-label="Emergency SOS" onClick={() => setSosActive(!sosActive)} className={`relative z-30 flex h-12 w-12 shrink-0 items-center justify-center rounded-full p-0 shadow-lg ${sosActive ? 'bg-red-600 text-white animate-pulse' : 'bg-red-100 text-red-600 hover:bg-red-200'}`}><ShieldAlert size={24} strokeWidth={2.5} /></Button>
        </div>
        <nav aria-label="Driver navigation" className="relative z-30 w-full overflow-x-auto overflow-y-visible pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
          <div className="flex min-w-max gap-2">
            {tabs.map(tab => { const Icon = tab.icon; const active = activeTab === tab.id; return <button key={tab.id} type="button" aria-current={active ? 'page' : undefined} onClick={() => setActiveTab(tab.id)} className={`relative z-30 inline-flex h-11 min-w-[112px] shrink-0 items-center justify-center gap-2 rounded-xl border px-4 text-sm font-bold leading-none opacity-100 transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${active ? 'border-brand-600 bg-brand-600 text-white shadow-md' : 'border-slate-200 bg-white text-slate-700 shadow-sm hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100'}`} style={{ opacity: 1, visibility: 'visible' }}><Icon aria-hidden="true" size={16} strokeWidth={2.5} className="shrink-0" /><span className="block whitespace-nowrap">{tab.label}</span></button>; })}
          </div>
        </nav>
      </div>
      <div className="relative z-0 mx-auto w-full max-w-lg flex-1 overflow-y-auto p-4 md:p-6">
        {activeTab === 'jobs' && <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">{availableJobs.length === 0 ? <div className="p-8 text-center text-slate-500">No jobs available right now.</div> : availableJobs.map(job => <div key={job.id} className="overflow-hidden rounded-[20px] border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-start justify-between"><div className="inline-flex items-center gap-1.5 rounded border border-brand-100 bg-brand-50 px-2 py-1 text-xs font-bold text-brand-700"><Clock size={12} /> {job.cargoType || 'Cargo'}</div><h3 className="text-lg font-black text-slate-800">₦{(job.suggestedBudget || 0).toLocaleString()}</h3></div><div className="relative mb-6 space-y-3"><div className="absolute bottom-4 left-[9px] top-4 w-0.5 bg-slate-200"/><div className="relative z-10 flex gap-3"><div className="mt-0.5 flex h-5 w-5 items-center justify-center rounded-full border-2 border-white bg-brand-100"><div className="h-2 w-2 rounded-full bg-brand-600"/></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Pickup</p><p className="text-sm font-bold text-slate-800">{job.origin}</p></div></div><div className="relative z-10 flex gap-3"><div className="mt-0.5 flex h-5 w-5 items-center justify-center rounded-full border-2 border-white bg-emerald-100"><MapPin size={10} className="text-emerald-600"/></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Dropoff</p><p className="text-sm font-bold text-slate-800">{job.destination}</p></div></div></div><div className="flex gap-3"><Button type="button" onClick={() => api.post('/bids/submit', { loadId: job.id, amount: job.suggestedBudget || 0, notes: 'Available immediately' }).then(() => alert('Bid submitted successfully!')).catch(e => alert('Failed to submit bid: ' + ((typeof e.response?.data?.error === 'object' ? JSON.stringify(e.response?.data?.error) : e.response?.data?.error) || e.message)))} className="flex-1 bg-brand-600 text-white font-bold py-3 rounded-xl"><CheckSquare size={18}/> Accept</Button><Button type="button" className="flex-1 bg-red-50 text-red-600 font-bold py-3 rounded-xl border border-red-200"><XCircle size={18}/> Decline</Button></div></div>)}</motion.div>}
        {activeTab === 'active-trip' && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4"><div className="rounded-[20px] bg-slate-800 p-5 text-white shadow-xl"><h3 className="text-2xl font-black">Apapa Port Delivery</h3><p className="mb-6 flex items-center gap-2 text-sm text-slate-300"><Navigation size={14}/> 14 mins away (5.2 km)</p><div className="flex gap-2"><Button type="button" className="flex-1 bg-white text-slate-900"><Navigation size={16}/> Navigate</Button><Button type="button" className="flex-1 bg-brand-500/30 text-brand-100"><MessageCircle size={16}/> Chat</Button></div></div><div className="rounded-[20px] border border-slate-200 bg-white p-5 shadow-sm"><h3 className="mb-4 flex items-center gap-2 font-bold text-slate-800"><CheckCircle2 className="text-emerald-500" size={18}/> Update Trip Status</h3><div className="mb-6 grid grid-cols-2 gap-3"><Button type="button" className="flex flex-col gap-2 rounded-xl border border-slate-200 bg-slate-50 p-4 text-slate-600"><Camera size={24}/><span className="text-center text-xs font-bold">Upload Cargo<br/>Photos</span></Button><Button type="button" className="flex flex-col gap-2 rounded-xl border border-slate-200 bg-slate-50 p-4 text-slate-600"><CheckSquare size={24}/><span className="text-center text-xs font-bold">Capture<br/>Signature</span></Button></div><Button type="button" className="w-full bg-emerald-600 py-3.5 font-black text-white">Complete Delivery <CheckCircle2 size={18}/></Button></div></motion.div>}
        {activeTab === 'earnings' && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4"><div className="rounded-[20px] bg-brand-600 p-6 text-white shadow-xl"><p className="text-xs font-bold uppercase text-brand-100">Available Balance</p><h2 className="text-4xl font-black">₦124,500<span className="text-xl text-brand-300">.00</span></h2><div className="mt-6 flex justify-between border-t border-brand-500/30 pt-6"><div><p className="text-[10px] font-bold uppercase text-brand-200">This Week</p><p className="font-bold">+ ₦45,000</p></div><Button type="button" className="rounded-full bg-white text-brand-700">Withdraw</Button></div></div><h3 className="mt-6 font-bold text-slate-800">Recent Transactions</h3></motion.div>}
        {activeTab === 'documents' && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4"><div className="rounded-[20px] border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><h3 className="font-bold text-slate-800">Compliance Documents</h3><span className="rounded border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-600">Verified</span></div><div className="space-y-3">{[{title:'Driver\'s License',status:'Valid - Expires 2027'},{title:'Vehicle Inspection Report',status:'Valid - Expires Dec 2026'},{title:'Insurance Certificate',status:'Pending Review'}].map((doc,i)=><div key={i} className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 p-3"><div><p className="text-sm font-bold text-slate-800">{doc.title}</p><p className="text-[10px] font-bold uppercase text-slate-500">{doc.status}</p></div><Button type="button" aria-label="Upload document" className="rounded-lg bg-brand-50 p-2 text-brand-600"><UploadCloud size={16}/></Button></div>)}</div></div></motion.div>}
      </div>
    </div>
  );
}
