import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {MapPin,Package,Truck,Clock,ChevronRight,Plus,Search,UserRound,Home,Activity,LogOut,ArrowLeft,Navigation,ShieldCheck} from 'lucide-react';
import TrackingScreen from './TrackingScreen';
import './styles.css';

const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
const api=axios.create({baseURL:API?`${API}${API.endsWith('/api')?'':'/api'}`:'/api',withCredentials:true,headers:{'Content-Type':'application/json'}});
const token=()=>localStorage.getItem('tc_token')||localStorage.getItem('token')||'';
api.interceptors.request.use(c=>{const t=token();if(t)c.headers.Authorization=`Bearer ${t}`;return c});

type Bid={id:string;amount:number;status:string;notes?:string|null};
type Load={id:string;title:string;origin:string;destination:string;weightKg:number;cargoType:string;status:string;suggestedBudget?:number|null;createdAt:string;bids?:Bid[]};
type Screen='login'|'home'|'loads'|'post'|'track';

function App(){
 const [screen,setScreen]=useState<Screen>(token()?'home':'login');
 const [phone,setPhone]=useState(''); const [pin,setPin]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const [loads,setLoads]=useState<Load[]>([]); const [message,setMessage]=useState(''); const [trackingId,setTrackingId]=useState('');
 const [form,setForm]=useState({title:'',origin:'',destination:'',weightKg:'',cargoType:'GENERAL',suggestedBudget:''});
 const loadData=async()=>{try{const r=await api.get('/loads/my-loads');setLoads(Array.isArray(r.data)?r.data:[])}catch{try{const r=await api.get('/loads/marketplace');setLoads(Array.isArray(r.data)?r.data:[])}catch{setLoads([])}}};
 useEffect(()=>{if(token())void loadData()},[]);
 const openTracking=(id:string)=>{setTrackingId(id);setScreen('track')};
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await api.post('/auth/login-pin',{phoneNumber:phone.trim(),pin,email:`${phone.trim()}@transconet.com`,role:'CUSTOMER'});const t=r.data?.token;if(!t)throw Error('No token returned');localStorage.setItem('tc_token',t);setScreen('home');await loadData()}catch(e:any){setError(e.response?.data?.error||'Unable to sign in. Check your phone and PIN.')}finally{setBusy(false)}};
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api.post('/loads/create',{...form,weightKg:Number(form.weightKg||0),suggestedBudget:form.suggestedBudget?Number(form.suggestedBudget):undefined});setMessage('Shipment created successfully');setForm({title:'',origin:'',destination:'',weightKg:'',cargoType:'GENERAL',suggestedBudget:''});await loadData();setScreen('loads')}catch(e:any){setError(e.response?.data?.error||'Could not create shipment.')}finally{setBusy(false)}};
 const logout=()=>{localStorage.removeItem('tc_token');localStorage.removeItem('token');setScreen('login');setLoads([])};
 if(screen==='login')return <main className="auth"><div className="auth-glow"/><div className="auth-card"><div className="logo"><span>Trans</span>Conet</div><p className="tag">Connecting Cargo with Capacity</p><div className="trust"><ShieldCheck size={18}/> Secure logistics platform</div><h1>Move cargo<br/>without friction.</h1><p className="muted">Book reliable transport, track shipments and manage your logistics from one place.</p><form onSubmit={login}><label>Mobile number<input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="08012345678" inputMode="tel"/></label><label>Account PIN<input required type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="••••••"/></label>{error&&<div className="error">{String(error)}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Continue'}</button></form><p className="hint">Your existing TransConet account is used. No new backend required.</p></div></main>;
 if(screen==='track')return <div className="app"><TrackingScreen loadId={trackingId} onBack={()=>setScreen('loads')}/></div>;
 return <div className="app"><header><button className="icon" onClick={()=>screen==='home'?null:setScreen('home')}>{screen==='home'?<div className="mini-logo"><b>Trans</b>Conet</div>:<ArrowLeft/>}</button><div className="header-title">{screen==='home'?'Good day':screen==='loads'?'My shipments':'New shipment'}</div><button className="icon" onClick={logout}><UserRound/></button></header>
 <section className="content">{screen==='home'?<><div className="hero"><div><span className="eyebrow">SHIPPER</span><h1>Where is your cargo going?</h1><p>Plan your next move in seconds.</p></div><button className="add" onClick={()=>setScreen('post')}><Plus/></button></div><button className="route-card" onClick={()=>setScreen('post')}><div className="route-icon"><MapPin/></div><div><b>Post a shipment</b><span>Tell us your pickup and destination</span></div><ChevronRight/></button><div className="section-head"><h2>Active shipments</h2><button onClick={()=>setScreen('loads')}>See all</button></div><LoadList loads={loads.slice(0,3)} onTrack={openTracking}/></>:screen==='loads'?<><div className="search"><Search size={18}/><input placeholder="Search shipments"/></div>{message&&<div className="success">{message}</div>}<LoadList loads={loads} onTrack={openTracking}/><button className="floating" onClick={()=>setScreen('post')}><Plus/> New shipment</button></>:<form className="post" onSubmit={create}><div className="form-card"><label>Shipment title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Electronics delivery"/></label><label>Pickup location<div className="input-icon"><MapPin/><input required value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})} placeholder="Lagos"/></div></label><label>Destination<div className="input-icon"><Navigation/><input required value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} placeholder="Abuja"/></div></label><div className="two"><label>Weight (kg)<input required type="number" min="1" value={form.weightKg} onChange={e=>setForm({...form,weightKg:e.target.value})}/></label><label>Budget (₦)<input type="number" value={form.suggestedBudget} onChange={e=>setForm({...form,suggestedBudget:e.target.value})} placeholder="Optional"/></label></div><label>Cargo type<select value={form.cargoType} onChange={e=>setForm({...form,cargoType:e.target.value})}><option>GENERAL</option><option>FRAGILE</option><option>PERISHABLE</option><option>VEHICLE</option><option>DOCUMENTS</option></select></label></div>{error&&<div className="error">{String(error)}</div>}<button className="primary" disabled={busy}>{busy?'Publishing…':'Publish shipment'}</button></form>}</section><nav><button className={screen==='home'?'active':''} onClick={()=>setScreen('home')}><Home/><span>Home</span></button><button className={screen==='loads'?'active':''} onClick={()=>setScreen('loads')}><Package/><span>Shipments</span></button><button onClick={()=>setScreen('post')}><Plus/><span>Post</span></button><button className={screen==='track'?'active':''} onClick={()=>{const active=loads.find(l=>!['DELIVERED','CANCELLED'].includes(l.status));if(active)openTracking(active.id);else setScreen('loads')}}><Activity/><span>Track</span></button></nav></div>}
function LoadList({loads,onTrack}:{loads:Load[];onTrack:(id:string)=>void}){if(!loads.length)return <div className="empty"><Package size={28}/><b>No shipments yet</b><span>Your published cargo will appear here.</span></div>;return <div className="loads">{loads.map(l=><article className="load" key={l.id}><div className="load-top"><div className="package"><Package/></div><span className="status">{l.status||'AVAILABLE'}</span></div><h3>{l.title}</h3><div className="locations"><span>{l.origin}</span><i/><span>{l.destination}</span></div><div className="meta"><span><Truck size={15}/>{l.weightKg||0} kg</span><span><Clock size={15}/>{new Date(l.createdAt).toLocaleDateString()}</span>{l.suggestedBudget&&<strong>₦{Number(l.suggestedBudget).toLocaleString()}</strong>}</div><div className="load-actions"><button onClick={()=>onTrack(l.id)}><Activity/> Track shipment</button>{l.bids?.length?<span>{l.bids.length} bid{l.bids.length===1?'':'s'}</span>:null}</div></article>)}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
