import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import adminApi from '../../api/adminClient';
import { useAdminAuth } from '../../context/AdminAuthContext';

const ROLES=['ADMIN','SUPER_ADMIN','PLATFORM_ADMIN','FINANCE_ADMIN','SUPPORT_ADMIN','COMPLIANCE_ADMIN','DEVELOPER'];

export default function AdminAccountsScreen() {
  const { admin } = useAdminAuth();
  const [admins,setAdmins]=useState([]); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [role,setRole]=useState('SUPPORT_ADMIN'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const refresh=useCallback(async()=>{try{const {data}=await adminApi.get('/admin/management');setAdmins(Array.isArray(data)?data:[]);setError('')}catch(e){setError(e?.response?.data?.error||'Unable to load administrator accounts.')}},[]);
  useFocusEffect(useCallback(()=>{refresh()},[refresh]));
  async function create(){if(!email.trim()||password.length<8){setError('Email and a password of at least 8 characters are required.');return}setBusy(true);setError('');try{await adminApi.post('/admin/management',{email:email.trim().toLowerCase(),password,role});setEmail('');setPassword('');Alert.alert('Administrator created','The new administrator account is now registered.');refresh()}catch(e){setError(e?.response?.data?.error||'Unable to create administrator.')}finally{setBusy(false)}}
  async function remove(id){Alert.alert('Delete administrator','This permanently removes the administrator and their active sessions.',[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await adminApi.delete(`/admin/management/${id}`);refresh()}catch(e){setError(e?.response?.data?.error||'Unable to delete administrator.')}}}])}
  if(admin?.role!=='SUPER_ADMIN') return <View style={s.center}><Text style={s.denied}>SUPER_ADMIN access required.</Text></View>;
  return <ScrollView style={s.screen} contentContainerStyle={s.content}><Text style={s.back}>‹ Administration</Text><Text style={s.eyebrow}>ADMINISTRATION</Text><Text style={s.title}>Admin Accounts</Text><Text style={s.sub}>Manage the administrator accounts through the existing protected management API.</Text>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.card}><Text style={s.cardTitle}>Create administrator</Text><TextInput style={s.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="admin@example.com"/><TextInput style={s.input} value={password} onChangeText={setPassword} secureTextEntry placeholder="Temporary password"/><View style={s.roles}>{ROLES.map(x=><Pressable key={x} onPress={()=>setRole(x)} style={[s.role,role===x&&s.active]}><Text style={role===x?s.activeText:s.roleText}>{x}</Text></Pressable>)}</View><Pressable style={s.button} onPress={create} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Create administrator</Text>}</Pressable></View>{admins.map(a=><View style={s.admin} key={a.id}><View style={{flex:1}}><Text style={s.adminEmail}>{a.email}</Text><Text style={s.meta}>{a.role} • {a.isActive?'ACTIVE':'INACTIVE'}</Text></View>{a.id!==admin.id&&<Pressable style={s.delete} onPress={()=>remove(a.id)}><Text style={s.deleteText}>Delete</Text></Pressable>}</View>)}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,paddingBottom:110},center:{flex:1,alignItems:'center',justifyContent:'center'},denied:{fontWeight:'900',color:'#B42318'},back:{fontSize:13,fontWeight:'900',color:'#155EEF',marginBottom:20},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#98A2B3'},title:{marginTop:6,fontSize:29,fontWeight:'900',color:'#0B1F44'},sub:{marginTop:7,marginBottom:18,fontSize:13,lineHeight:19,color:'#667085'},error:{marginBottom:12,color:'#D92D20',fontWeight:'700'},card:{padding:17,borderRadius:19,backgroundColor:'#fff',borderWidth:1,borderColor:'#EAECF0'},cardTitle:{fontSize:16,fontWeight:'900',color:'#101828'},input:{height:50,borderRadius:11,borderWidth:1,borderColor:'#D0D5DD',paddingHorizontal:14,marginTop:10,backgroundColor:'#fff'},roles:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:10},role:{paddingHorizontal:9,paddingVertical:8,borderRadius:9,borderWidth:1,borderColor:'#D0D5DD'},active:{backgroundColor:'#155EEF',borderColor:'#155EEF'},roleText:{fontSize:9,fontWeight:'800',color:'#475467'},activeText:{fontSize:9,fontWeight:'800',color:'#fff'},button:{height:50,borderRadius:12,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center',marginTop:13},buttonText:{color:'#fff',fontWeight:'900'},admin:{marginTop:10,padding:15,borderRadius:15,backgroundColor:'#fff',borderWidth:1,borderColor:'#EAECF0',flexDirection:'row',alignItems:'center'},adminEmail:{fontSize:14,fontWeight:'900',color:'#344054'},meta:{marginTop:4,fontSize:10,color:'#667085',fontWeight:'700'},delete:{paddingHorizontal:10,paddingVertical:8,borderRadius:9,borderWidth:1,borderColor:'#FDA29B'},deleteText:{fontSize:10,fontWeight:'900',color:'#B42318'}});
