import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import adminApi from '../../api/adminClient';
import { useAdminAuth } from '../../context/AdminAuthContext';

const MODULES=[
 ['Live Trips','/admin/loads','Operations'],['Risk & Fraud','/admin/risk-alerts','Compliance'],['Audit Logs','/admin/audit-logs','Security'],['Reports Center','/admin/reports','Reports'],['API Management','/admin/api-keys','Developer'],['Role & Permissions','/admin/users','Administration'],['Fleet Management','/admin/fleet','Operations'],['User Management','/admin/users','Support'],['Verifications','/admin/verifications','Compliance'],['Subscriptions','/admin/subscriptions','Finance'],['Security Events','/admin/security-events','Security'],['Platform Config','/admin/config','Platform'],['System Status','/admin/system-status','Developer'],['AI Insights','/admin/ai-insights','AI'],['Notifications','/admin/notifications','Platform'],['Marketing','/admin/marketing','Platform'],['Content','/admin/content','Platform'],['Partners','/admin/partners','Platform'],['AI Models','/admin/ai-models','Developer'],['Database Health','/admin/db-health','Developer'],['Redis Monitoring','/admin/redis-monitoring','Developer'],['Backup History','/admin/backup-history','Developer'],['Developer Logs','/admin/developer-logs','Developer']
];
export default function AdminDashboardScreen({navigation}){const{admin,logout}=useAdminAuth();const[metrics,setMetrics]=useState(null);const[error,setError]=useState('');const refresh=useCallback(async()=>{try{const{data}=await adminApi.get('/admin/metrics');setMetrics(data?.metrics||data);setError('')}catch(e){setError(e?.response?.data?.error||'Unable to load live administration metrics.')}},[]);useFocusEffect(useCallback(()=>{refresh()},[refresh]));return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>ADMINISTRATION</Text><Text style={styles.title}>Control Center</Text><Text style={styles.meta}>{admin?.email} • {admin?.role}</Text></View><Pressable style={styles.logout} onPress={logout}><Text style={styles.logoutText}>Sign out</Text></Pressable></View>{error?<Text style={styles.error}>{error}</Text>:null}<View style={styles.metrics}>{metrics?Object.entries(metrics).slice(0,6).map(([key,value])=><View key={key} style={styles.metric}><Text style={styles.metricValue}>{typeof value==='number'?value.toLocaleString():String(value??'—')}</Text><Text style={styles.metricLabel}>{key.replace(/_/g,' ')}</Text></View>):<ActivityIndicator color="#155EEF"/>}</View>{admin?.role==='SUPER_ADMIN'&&<Pressable style={styles.accounts} onPress={()=>navigation.navigate('AdminAccounts')}><Text style={styles.accountsTitle}>Administrator Accounts</Text><Text style={styles.accountsText}>Create, review and remove privileged administrator accounts.</Text></Pressable>}<Text style={styles.section}>Management modules</Text><View style={styles.grid}>{MODULES.map(([name,path,group])=><Pressable key={path+name} style={styles.module} onPress={()=>navigation.navigate('AdminModule',{name,path})}><Text style={styles.moduleGroup}>{group}</Text><Text style={styles.moduleName}>{name}</Text><Text style={styles.moduleArrow}>›</Text></Pressable>)}</View></ScrollView></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:18,paddingBottom:110},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#155EEF'},title:{marginTop:5,fontSize:28,fontWeight:'900',color:'#0B1F44'},meta:{marginTop:5,fontSize:11,color:'#667085'},logout:{paddingHorizontal:12,paddingVertical:9,borderRadius:10,borderWidth:1,borderColor:'#D0D5DD'},logoutText:{fontSize:11,fontWeight:'900',color:'#475467'},error:{marginTop:14,color:'#D92D20',fontSize:12,fontWeight:'700'},metrics:{marginTop:18,flexDirection:'row',flexWrap:'wrap',gap:9},metric:{width:'31.8%',minHeight:82,padding:11,borderRadius:15,backgroundColor:'#fff',borderWidth:1,borderColor:'#EAECF0'},metricValue:{fontSize:17,fontWeight:'900',color:'#155EEF'},metricLabel:{marginTop:5,fontSize:9,fontWeight:'800',textTransform:'uppercase',color:'#98A2B3'},accounts:{marginTop:16,padding:16,borderRadius:16,backgroundColor:'#071A33'},accountsTitle:{fontSize:15,fontWeight:'900',color:'#fff'},accountsText:{marginTop:5,fontSize:11,lineHeight:17,color:'#B8C7D9'},section:{marginTop:24,marginBottom:10,fontSize:17,fontWeight:'900',color:'#101828'},grid:{gap:9},module:{minHeight:72,padding:14,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:'#EAECF0'},moduleGroup:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#98A2B3',textTransform:'uppercase'},moduleName:{marginTop:5,fontSize:15,fontWeight:'900',color:'#344054'},moduleArrow:{position:'absolute',right:15,top:25,fontSize:22,color:'#155EEF'}});
