import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import api from '../../api/client';

export default function FindTruckScreen({ navigation }) {
  const [loads,setLoads]=useState([]); const [busy,setBusy]=useState(true); const [running,setRunning]=useState(null); const [error,setError]=useState('');
  async function loadMine(){setBusy(true);setError('');try{const {data}=await api.get('/my-loads');setLoads(Array.isArray(data)?data:[]);}catch(e){setError(e?.response?.data?.error||'Unable to load your shipments.');}finally{setBusy(false);}}
  useEffect(()=>{loadMine();},[]);
  async function autoMatch(load){setRunning(load.id);setError('');try{const {data}=await api.post(`/loads/${load.id}/auto-match`);const matches=data?.matches||data?.matchedDrivers||[];if(matches.length){setLoads(prev=>prev.map(x=>x.id===load.id?{...x,__matches:matches}:x));}else{setError('The live matching service returned no transporter matches for this shipment yet.');}}catch(e){setError(e?.response?.data?.error||'Unable to run live transporter matching.');}finally{setRunning(null);}}
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <Text style={styles.eyebrow}>SHIPPER</Text><Text style={styles.title}>Find a Truck</Text><Text style={styles.subtitle}>Run TransConet's live transporter matching against one of your posted shipments.</Text>
    {error?<Text style={styles.error}>{error}</Text>:null}
    {busy?<ActivityIndicator size="large" color="#4169E1"/>:loads.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No posted shipments</Text><Text style={styles.emptyText}>Post your cargo first, then use Find a Truck to run matching.</Text><Pressable style={styles.button} onPress={()=>navigation.navigate('PostCargo')}><Text style={styles.buttonText}>Post Cargo</Text></Pressable></View>:loads.map(load=><View key={load.id} style={styles.card}>
      <Text style={styles.cardTitle}>{load.title||'Cargo Freight'}</Text><Text style={styles.meta}>{load.cargoType||'GENERAL'} • {load.weightKg||0} kg</Text>
      <View style={styles.route}><Text style={styles.routeLabel}>PICKUP</Text><Text style={styles.routeText}>{load.origin}</Text><Text style={styles.routeLabel}>DESTINATION</Text><Text style={styles.routeText}>{load.destination}</Text></View>
      <Pressable style={styles.button} onPress={()=>autoMatch(load)} disabled={!!running}>{running===load.id?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Find Matching Transporters</Text>}</Pressable>
      {load.__matches?.map((m,i)=><View key={m.driverId||i} style={styles.match}><Text style={styles.matchTitle}>Matched transporter</Text><Text style={styles.meta}>Driver: {m.driverId||'Verified driver'}</Text>{m.matchScore!=null?<Text style={styles.score}>Match score: {m.matchScore}%</Text>:null}</View>)}
    </View>)}
  </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,paddingBottom:110},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.4,color:'#4169E1'},title:{marginTop:5,fontSize:30,fontWeight:'900',color:'#0B1F44'},subtitle:{marginTop:8,marginBottom:20,fontSize:14,lineHeight:21,color:'#667085'},error:{marginBottom:12,color:'#D92D20',fontSize:13,fontWeight:'700'},empty:{backgroundColor:'#fff',borderRadius:20,padding:24,alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'900',color:'#0B1F44'},emptyText:{marginTop:7,textAlign:'center',lineHeight:20,color:'#667085'},card:{backgroundColor:'#fff',borderRadius:20,padding:18,marginBottom:14,borderWidth:1,borderColor:'#EAECF0'},cardTitle:{fontSize:18,fontWeight:'900',color:'#101828'},meta:{marginTop:5,fontSize:12,color:'#667085',fontWeight:'700'},route:{marginVertical:16,paddingLeft:12,borderLeftWidth:2,borderLeftColor:'#B2DDFF'},routeLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#98A2B3',marginTop:5},routeText:{fontSize:14,fontWeight:'800',color:'#344054',marginTop:3,marginBottom:8},button:{height:50,borderRadius:12,backgroundColor:'#4169E1',alignItems:'center',justifyContent:'center',marginTop:4},buttonText:{color:'#fff',fontSize:13,fontWeight:'900'},match:{marginTop:12,padding:13,borderRadius:12,backgroundColor:'#ECFDF3'},matchTitle:{fontSize:13,fontWeight:'900',color:'#027A48'},score:{marginTop:4,fontSize:12,fontWeight:'800',color:'#039855'}});
