import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import api from '../../api/client';

export default function MyShipmentsScreen(){const [loads,setLoads]=useState([]);const [busy,setBusy]=useState(true);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{setBusy(true);try{const {data}=await api.get('/my-loads');setLoads(Array.isArray(data)?data:[]);setError('');}catch(e){setError(e?.response?.data?.error||'Unable to retrieve your shipments.');}finally{setBusy(false);}},[]);useFocusEffect(useCallback(()=>{refresh();},[refresh]));
 async function accept(bidId){try{await api.post('/bids/accept',{bidId});await refresh();}catch(e){setError(e?.response?.data?.error||'Unable to accept this bid.');}}
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>SHIPPER</Text><Text style={styles.title}>My Shipments</Text><Text style={styles.subtitle}>Live shipments and transporter bids from your TransConet account.</Text>{error?<Text style={styles.error}>{error}</Text>:null}{busy?<ActivityIndicator size="large" color="#4169E1"/>:loads.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No shipments yet</Text><Text style={styles.emptyText}>Post cargo to create your first shipment.</Text></View>:loads.map(load=><View style={styles.card} key={load.id}><View style={styles.row}><Text style={styles.cardTitle}>{load.title||'Cargo Freight'}</Text><Text style={styles.status}>{load.status||'AVAILABLE'}</Text></View><Text style={styles.meta}>{load.cargoType||'GENERAL'} • {load.weightKg||0} kg</Text><Text style={styles.route}>{load.origin} → {load.destination}</Text>{load.bids?.length?<View style={styles.bids}><Text style={styles.bidsTitle}>{load.bids.length} bid{load.bids.length>1?'s':''}</Text>{load.bids.map(b=><View style={styles.bid} key={b.id}><View><Text style={styles.bidPrice}>₦{Number(b.amount||0).toLocaleString()}</Text><Text style={styles.meta}>{b.driver?.phoneNumber||'Transporter'}</Text>{b.driver?.transporterProfile?.verificationLevel?<Text style={styles.verified}>Verified: {b.driver.transporterProfile.verificationLevel}</Text>:null}</View>{b.status==='PENDING'?<Pressable style={styles.accept} onPress={()=>accept(b.id)}><Text style={styles.acceptText}>Accept</Text></Pressable>:<Text style={styles.meta}>{b.status}</Text>}</View>)}</View>:<Text style={styles.noBids}>No bids received yet.</Text>}</View>)}</ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,paddingBottom:110},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.4,color:'#4169E1'},title:{marginTop:5,fontSize:30,fontWeight:'900',color:'#0B1F44'},subtitle:{marginTop:8,marginBottom:18,fontSize:14,lineHeight:21,color:'#667085'},error:{marginBottom:12,color:'#D92D20',fontWeight:'700'},empty:{padding:24,borderRadius:20,backgroundColor:'#fff',alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'900',color:'#0B1F44'},emptyText:{marginTop:7,color:'#667085'},card:{padding:18,borderRadius:20,backgroundColor:'#fff',marginBottom:14,borderWidth:1,borderColor:'#EAECF0'},row:{flexDirection:'row',justifyContent:'space-between',gap:8},cardTitle:{flex:1,fontSize:17,fontWeight:'900',color:'#101828'},status:{fontSize:9,fontWeight:'900',color:'#4169E1'},meta:{marginTop:4,fontSize:11,color:'#667085',fontWeight:'700'},route:{marginTop:14,fontSize:14,fontWeight:'800',color:'#344054'},bids:{marginTop:16,paddingTop:12,borderTopWidth:1,borderTopColor:'#EAECF0'},bidsTitle:{fontSize:12,fontWeight:'900',color:'#344054'},bid:{marginTop:9,padding:12,borderRadius:12,backgroundColor:'#F8FAFC',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},bidPrice:{fontSize:15,fontWeight:'900',color:'#039855'},verified:{marginTop:3,fontSize:10,fontWeight:'800',color:'#027A48'},accept:{paddingHorizontal:13,paddingVertical:9,borderRadius:10,backgroundColor:'#4169E1'},acceptText:{color:'#fff',fontSize:11,fontWeight:'900'},noBids:{marginTop:14,color:'#667085',fontSize:12}}
