import React, { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import api from '../../api/client';

export default function PostCargoScreen(){
 const [name,setName]=useState('');const [description,setDescription]=useState('');const [category,setCategory]=useState('GENERAL_MERCHANDISE');const [weight,setWeight]=useState('');const [packaging,setPackaging]=useState('');const [origin,setOrigin]=useState('');const [destination,setDestination]=useState('');const [budget,setBudget]=useState('250000');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function submit(){setMessage('');if(!name.trim()||!description.trim()||!weight||!packaging||!origin.trim()||!destination.trim()){setMessage('Complete the cargo, weight, packaging, pickup and delivery fields.');return;}setBusy(true);try{const {data}=await api.post('/loads/create',{title:name.trim(),description,cargoType:category,weightKg:Number(weight),origin:origin.trim(),destination:destination.trim(),suggestedBudget:Number(budget)||null,isEscrowEnabled:false});const load=data?.data||data?.load;if(!load?.id){setMessage('Cargo was not returned with a valid load ID.');return;}let pricing='';let matching='';try{const p=await api.post(`/loads/${load.id}/optimize-price`);if(p.data?.optimizedPrice)pricing=`Optimized price: ₦${Number(p.data.optimizedPrice).toLocaleString()}`;}catch(_){}try{const m=await api.post(`/loads/${load.id}/auto-match`);const matches=m.data?.matches||m.data?.matchedDrivers||[];matching=matches.length?`Live matches found: ${matches.length}`:'No transporter match returned yet.';}catch(_){}setMessage(`Cargo posted successfully.\nLoad ID: ${load.id}\n${pricing}${pricing?'\n':''}${matching}`);setName('');setDescription('');setWeight('');setPackaging('');setOrigin('');setDestination('');}catch(e){setMessage(e?.response?.data?.error||'Unable to post cargo.');}finally{setBusy(false);}}
 const cats=['GENERAL_MERCHANDISE','FRAGILE','PERISHABLE','ELECTRONICS','MEDICAL','CHEMICALS','MACHINERY','AUTOMOTIVE','CONSTRUCTION','OTHER'];const packs=['PALLET','BOX','BAG','CRATE','DRUM','LOOSE','OTHER'];
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>SHIPPER</Text><Text style={styles.title}>Post Cargo</Text><Text style={styles.subtitle}>Create a real TransConet shipment and send it through the existing pricing and transporter-matching services.</Text>
 {message?<Text style={styles.message}>{message}</Text>:null}<View style={styles.card}>
 <Field label="Cargo name" value={name} onChange={setName} placeholder="e.g. 10 bags of rice"/><Field label="Cargo description" value={description} onChange={setDescription} placeholder="Describe your cargo" multiline/>
 <Text style={styles.label}>Category</Text><View style={styles.chips}>{cats.map(x=><Pressable key={x} onPress={()=>setCategory(x)} style={[styles.chip,category===x&&styles.chipActive]}><Text style={category===x?styles.chipTextActive:styles.chipText}>{x.replace(/_/g,' ')}</Text></Pressable>)}</View>
 <Field label="Total weight (kg)" value={weight} onChange={setWeight} placeholder="5000" numeric/><Text style={styles.label}>Packaging</Text><View style={styles.chips}>{packs.map(x=><Pressable key={x} onPress={()=>setPackaging(x)} style={[styles.chip,packaging===x&&styles.chipActive]}><Text style={packaging===x?styles.chipTextActive:styles.chipText}>{x}</Text></Pressable>)}</View>
 <Field label="Pickup location" value={origin} onChange={setOrigin} placeholder="Apapa Port, Lagos"/><Field label="Delivery location" value={destination} onChange={setDestination} placeholder="Challenge, Ibadan, Oyo State"/><Field label="Suggested budget (₦)" value={budget} onChange={setBudget} placeholder="250000" numeric/>
 <Pressable style={styles.button} onPress={submit} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Post Cargo</Text>}</Pressable>
 </View></ScrollView>;
}
function Field({label,value,onChange,placeholder,multiline,numeric}){return <View><Text style={styles.label}>{label}</Text><TextInput style={[styles.input,multiline&&styles.textarea]} value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#98A2B3" multiline={!!multiline} keyboardType={numeric?'numeric':'default'}/></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,paddingBottom:110},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.4,color:'#4169E1'},title:{marginTop:5,fontSize:30,fontWeight:'900',color:'#0B1F44'},subtitle:{marginTop:8,marginBottom:18,fontSize:14,lineHeight:21,color:'#667085'},message:{marginBottom:14,padding:14,borderRadius:14,backgroundColor:'#ECFDF3',color:'#027A48',fontSize:13,fontWeight:'700',lineHeight:19},card:{backgroundColor:'#fff',borderRadius:20,padding:18,borderWidth:1,borderColor:'#EAECF0'},label:{marginTop:12,marginBottom:7,fontSize:13,fontWeight:'800',color:'#344054'},input:{height:52,borderWidth:1,borderColor:'#D0D5DD',borderRadius:12,paddingHorizontal:14,backgroundColor:'#fff',fontSize:15,color:'#101828'},textarea:{height:100,paddingTop:14,textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:10,paddingVertical:9,borderRadius:10,borderWidth:1,borderColor:'#D0D5DD',backgroundColor:'#fff'},chipActive:{backgroundColor:'#4169E1',borderColor:'#4169E1'},chipText:{fontSize:10,fontWeight:'800',color:'#475467'},chipTextActive:{fontSize:10,fontWeight:'800',color:'#fff'},button:{height:54,borderRadius:13,backgroundColor:'#4169E1',alignItems:'center',justifyContent:'center',marginTop:20},buttonText:{color:'#fff',fontSize:15,fontWeight:'900'}});
